# /etc/opt/traefik/config/dynamic/acme_routes.yml
# Ref: https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
# yamllint disable rule:document-start rule:document-end
http:
  routers:
    pve1: &acme_service
      rule: Host(`pve1.{{ site.url }}`)
      entryPoints: websecure
      service: s403@file
      tls:
        options: intermediate@file
        certResolver: le-http-production
    pve2:
      <<: *acme_service
      rule: Host(`pve2.{{ site.url }}`)
    pbs2:
      <<: *acme_service
      rule: Host(`pbs2.{{ site.url }}`)
    router:
      <<: *acme_service
      rule: Host(`router.{{ site.url }}`)
    vpnui:
      <<: *acme_service
      rule: Host(`vpn-ui.{{ site.url }}`)
  services:
    s403:
      loadBalancer:
        servers:
          - url: https://www.{{ site.url }}/error/403.html
