# /etc/opt/traefik/config/dynamic/routes.yml
# References:
#   - https://www.simplecto.com/use-traefik-with-nginx-apache-caddyserver-serve-static-files/
#   - https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
# yamllint disable rule:document-start rule:document-end
http:
  routers:
    traefik: &service
      rule: Host(`webproxy.{{ site.url }}`)
      entryPoints: websecure
      service: api@internal
      middlewares:
        - authelia@file
        - secure-headers@file
      tls:
        options: intermediate@file
        certResolver: le-http-production
    root:
      <<: *service
      rule: Host(`{{ site.url }}`)
      service: nginx@file
      middlewares:
        - www-redirect@file
    homepage:
      <<: *service
      rule: Host(`dash.{{ site.url }}`)
      service: homepage@file
    static-files:
      <<: *service
      rule: Host(`www.{{ site.url }}`) || Host(`static.{{ site.url }}`) || Host(`blog.{{ site.url }}`) || Host(`wifi.{{ site.url }}`)
      service: nginx@file
      middlewares:
        - gzip@file
        - secure-headers@file
    # example-static:
    #   <<: *service
    #   rule: (Host(`example.{{ site.url }}`) && PathPrefix(`/static`))
    #   service: nginx@file
    #   middlewares:
    #     - gzip@file
    #     - static-strip-prefix@file
  services:
    homepage:
      loadBalancer:
        servers:
          - url: http://dash.{{ site.url }}:3000/
    nginx:
      loadBalancer:
        servers:
          - url: http://static.{{ site.url }}:8100/
