# /etc/opt/traefik/config/dynamic/aa_firewall.yml
# Ref:
#   - https://doc.traefik.io/traefik/reference/routing-configuration/http/middlewares/ratelimit/  
#   - https://doc.traefik.io/traefik/reference/routing-configuration/http/middlewares/ipallowlist/
# yamllint disable rule:document-start rule:document-end
http:
  routers:
    firewall:
      rule: "PathPrefix(`/wp-admin`, `/phpmyadmin`, `/pma`, `/backup`) || PathRegexp(`.*\\.(env|git|htaccess|htpasswd|config|yml|yaml)$`)"
      entryPoints: websecure
      tls: {}
      service: "noop@internal" # Sends traffic nowhere since we are blocking it
      middlewares:
        - block-requests

  middlewares:
    block-requests:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32" # Effectively blocks everyone, 403