# /etc/opt/victoriametrics/prometheus.yml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert.{{ site.url }}:8880']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['metrics.{{ site.url }}:8428']
  - job_name: 'victorialogs'
    static_configs:
      - targets: ['logs.{{ site.url }}:9428']
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['log-collector.{{ site.url }}:2020/api/v1/metrics/prometheus']
  - job_name: gatus
    # https://github.com/TwiN/gatus?tab=readme-ov-file#metrics
    static_configs:
      - targets: ['uptime.{{ site.url }}:8080']
  - job_name: 'ntfy'
    static_configs:
      - targets: ['push.{{ site.url }}:2587']
  - job_name: pve
    # https://github.com/prometheus-pve/prometheus-pve-exporter?tab=readme-ov-file#exported-metrics
    static_configs:
      - targets:  # Proxmox VE nodes
        - pve1.{{ site.url }}
        - pve2.{{ site.url }}
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['0']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve_exporter.{{ site.url }}:9221
  - job_name: 'node_exporter'
    # https://github.com/prometheus/node_exporter?tab=readme-ov-file#collectors
    static_configs:
      - targets: ['{{ pve1.ip }}:9100']
