# /etc/opt/victoriametrics/prometheus.yml

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmalert'
    static_configs:
      - targets: ['alert.{{ site.url }}:8880']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['metrics.{{ site.url }}:8428']
  - job_name: 'victorialogs'
    static_configs:
      - targets: ['logs.{{ site.url }}:9428']
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['log-collector.{{ site.url }}:2020/api/v1/metrics/prometheus']
  - job_name: gatus
    static_configs:
      - targets: ['uptime.{{ site.url }}:8080']
  - job_name: pve
    static_configs:
      - targets:  # Proxmox VE nodes
        - {{ pve1.ip }}
        - {{ pve2.ip }}
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['0']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve_exporter.{{ site.url }}:9221
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.containers.internal:9100']
