# /etc/opt/victoriametrics/prometheus.yml
# Ref: https://prometheus.io/docs/prometheus/latest/configuration/configuration
---
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert.{{ site.url }}:8880']
    metrics_path: /metrics
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['metrics.{{ site.url }}:8428']
    basic_auth:
      username: 'admin'
      password: '${VM_ADMIN_PASSWORD}'
    metrics_path: /metrics
  - job_name: 'victorialogs'
    static_configs:
      - targets: ['logs.{{ site.url }}:9428']
    metrics_path: /metrics
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['log-collector.{{ site.url }}:2020']
    metrics_path: /api/v1/metrics/prometheus
  - job_name: gatus
    # https://github.com/TwiN/gatus?tab=readme-ov-file#metrics
    static_configs:
      - targets: ['uptime.{{ site.url }}:8080']
    metrics_path: /metrics
  - job_name: 'ntfy'
    static_configs:
      - targets: ['push.{{ site.url }}:2587']
    metrics_path: /metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - host.containers.internal:9100
          # - pve1.{{ site.url }}:9100
    metrics_path: /metrics
    relabel_configs:
      - target_label: instance
        replacement: secsvcs.{{ site.url }}:9100
...
