# /etc/opt/vmagent/prometheus.yml
# Ref: https://prometheus.io/docs/prometheus/latest/configuration/configuration
---
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['metric-collector.{{ site.url }}:8429']
    metrics_path: /metrics
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['log-collector.{{ site.url }}:2020']
    metrics_path: /api/v1/metrics/prometheus
  - job_name: 'finance_exporter'
    static_configs:
      - targets: ['finance-exporter.{{ site.url }}:8002']
    metrics_path: /
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - host.containers.internal:9100
          # - pve2.{{ site.url }}:9100
    metrics_path: /metrics
    relabel_configs:
      - target_label: instance
        replacement: secsvcs.{{ site.url }}:9100
...
