# /etc/opt/vmagent/prometheus.yml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['metric-collector.{{ site.url }}:8429']
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['log-collector.{{ site.url }}:2020/api/v1/metrics/prometheus']
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['host.containers.internal:9100']
