# /etc/opt/vmagent/prometheus.yml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['metric-collector.{{ site.url }}:8429']
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['log-collector.{{ site.url }}:2020/api/v1/metrics/prometheus']
  - job_name: 'node_exporter'
    # https://github.com/prometheus/node_exporter?tab=readme-ov-file#collectors
    static_configs:
      - targets: ['{{ pve2.ip }}:9100']
