# /etc/opt/traefik/config/dynamic/routes.yml
# References:
#   - https://www.simplecto.com/use-traefik-with-nginx-apache-caddyserver-serve-static-files/
#   - https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
# yamllint disable rule:document-start rule:document-end
http:
  routers:
    traefik: &service
      rule: Host(`homeproxy.{{ site.url }}`)
      entryPoints: websecure
      service: api@internal
      middlewares:
        - authelia@file
        - secure-headers@file
      tls:
        options: intermediate@file
        certResolver: le-http-production
    hass:
      <<: *service
      rule: Host(`home.{{ site.url }}`)
      service: hass@file
    z2m:
      <<: *service
      rule: Host(`zigbee.{{ site.url }}`)
      service: z2m@file
    esphome:
      <<: *service
      rule: Host(`iot.{{ site.url }}`)
      service: esphome@file
  services:
    hass:
      loadBalancer:
        servers:
          - url: http://home.{{ site.url }}:8123/
          # TODO: add extension then enable
          # - url: http://home.{{ site.url }}:8123/auth/oidc/welcome
    z2m:
      loadBalancer:
        servers:
          - url: http://zigbee.{{ site.url }}:8080/
    esphome:
      loadBalancer:
        servers:
          - url: http://iot.{{ site.url }}:6052/
