# /etc/opt/grafana/datasources.yml
# Ref:
#   https://github.com/VictoriaMetrics/victoriametrics-datasource
#   https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
---
apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: victoriametrics-datasource
    access: proxy
    url: http://metrics.{{ site.url }}:8428
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: '${VM_ADMIN_PASSWORD}'
    isDefault: true

  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url: http://logs.{{ site.url }}:9428

  # - name: VictoriaMetrics
  #   type: prometheus
  #   access: proxy
  #   url: http://metrics.{{ site.url }}:8428
  #   isDefault: true
  #   jsonData:
  #     prometheusType: Prometheus
  #     prometheusVersion: 2.24.0
...
