# This is only the ldap config, you also need to enable ldap support in the main config file
# of Grafana. See https://grafana.com/docs/grafana/latest/auth/ldap/#enable-ldap
# You can test that it is working correctly by trying usernames at: https://graph.{{ site.url }}/admin/ldap
# Ref: https://github.com/lldap/lldap/blob/main/example_configs/grafana_ldap_config.toml
# Not currently in use (OIDC supplies auth and group info)

# TODO: fix auth error
# log: Cause: bind failed with error: LDAP Result Code 49 \"Invalid Credentials\": " method=POST

[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "ldap.{{ site.url }}"
# Default port is 389 or 636 if use_ssl = true
port = 6360
# Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
use_ssl = true
# If set to true, use LDAP with STARTTLS instead of LDAPS
start_tls = false
# set to true if you want to skip SSL cert validation
ssl_skip_verify = false
# set to the path to your root CA certificate or leave unset to use system defaults
root_ca_cert = "/certificates/ca.chain.pem"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"

# Search user bind dn
bind_dn = "uid=grafana,ou=people,dc={{ site.url.replace('.', ',dc=') }}"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = """${LDAP_BIND_PASSWORD}"""

# User search filter
search_filter = "(uid=%s)"
# If you want to limit to only users of a specific group use this instead:
# search_filter = "(&(uid=%s)(memberOf=cn=<your group>,ou=groups,dc={{ site.url.replace('.', ',dc=') }}))"

# An array of base dns to search through
search_base_dns = ["dc={{ site.url.replace('.', ',dc=') }}"]

# Specify names of the LDAP attributes your LDAP uses
[servers.attributes]
member_of = "memberOf"
email = "mail"
name = "displayName"
surname = "sn"
username = "uid"

# If you want to map your ldap groups to grafana's groups, see: https://grafana.com/docs/grafana/latest/auth/ldap/#group-mappings
# Map lldap's admin group to grafana's admin
[[servers.group_mappings]]
group_dn = "cn=lldap_password_manager,ou=groups,dc={{ site.url.replace('.', ',dc=') }}"
org_role = "Admin"
grafana_admin = true
