# /etc/opt/finance_exporter/config.yaml
# Ref: https://github.com/babraham/finance-exporter/blob/main/README.md
---
port: 8002
address: 0.0.0.0
metric_prefix: finance
min_interval: 15
# If set, each ticker will load labels from each source
# before the first run. Slows down startup time but
# necessary if using multiple sources that do not
# provide all labels.
update_cache_on_startup: false

tickers:{% for ticker in personal.ticker_symbols %}
  - '{{ ticker }}'{% endfor %}

sources:
  - name: yahoo
    interval: 300
    plugin: yfinance

    metrics:
      #current_price:
      #  item: regularMarketPrice
      #  type: Gauge
      #  help: Current Market Price of Asset
      open_price:
        item: regularMarketOpen
        type: Gauge
        help: Day Open Price
      previous_close:
        item: regularMarketPreviousClose
        type: Gauge
        help: Previous Closing Price
      day_high:
        item: regularMarketDayHigh
        type: Gauge
        help: Day High Price
      day_low:
        item: regularMarketDayLow
        type: Gauge
        help: Day Low Price
      52wk_high:
        item: fiftyTwoWeekHigh
        type: Gauge
        help: Fifty-Two Week High
      52wk_low:
        item: fiftyTwoWeekLow
        type: Gauge
        help: Fifty-Two Week Low
      target_median_price:
        item: targetMedianPrice
        type: Gauge
        help: Target Price (Median)
        #volume:
        #  item: regularMarketVolume
        #  type: Gauge
        #  help: Current Market Volume
        #avg_volume:
        #  item: averageVolume
        #  type: Gauge
        #  help: Average Volume
      avg_10day_volume:
        item: averageDailyVolume10Day
        type: Gauge
        help: Average Daily Volume (10 Day)
      held_insiders_percent:
        item: heldPercentInsiders
        type: Gauge
        help: Percent of Shared Held by Insiders
      pe_forward:
        item: forwardPE
        type: Gauge
        help: Forward Price-to-Earnings Ratio
      pe_trailing:
        item: trailingPE
        type: Gauge
        help: Trailing Price-to-Earnings Ratio
      shorts:
        item: sharesShort
        type: Gauge
        help: Number of shares short
      beta:
        item: beta
        type: Gauge
        help: Beta

    labels:
      ticker: symbol
      type: quoteType
      name: shortName
      exchange: exchange
      recommendation: recommendationKey
      sector: sector
...
