{
 "title": "Gatus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "victoriametrics-metrics-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Success rate",
   "type": "gauge",
   "description": "Number of successful results compared to the total number of results during the current interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[$__rate_interval])) by (key) / sum(rate(gatus_results_total[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gatus_results_duration_seconds", "legendFormat": "{{key}}" }
   ]
  },
  {
   "title": "Success rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[$__rate_interval])) by (key) / sum(rate(gatus_results_total[$__rate_interval])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total results per minute",
   "type": "graph",
   "description": "Number of results per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total[$__rate_interval])*60) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Successful results per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[$__rate_interval])*60) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Unsuccessful results per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"false\"}[$__rate_interval])*60) by (key)",
     "legendFormat": "{{key}} "
    }
   ]
  }
 ]
}