{
 "title": "ntfy App",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "label": "Datasource",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ntfy_visitors_total, job)"
    }
   },
   { "name": "rate", "label": "Rate", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Published",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ntfy_messages_published_success{job=\"$job\"}",
     "legendFormat": "Messages cached"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ntfy_messages_cached_total{job=\"$job\"}",
     "legendFormat": "Messages cached"
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ntfy_visitors_total{job=\"$job\"}",
     "legendFormat": "Visitors"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ntfy_users_total{job=\"$job\"}",
     "legendFormat": "Visitors"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ntfy_topics_total{job=\"$job\"}",
     "legendFormat": "Topics"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ntfy_subscribers_total{job=\"$job\"}",
     "legendFormat": "Subscribers"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Messages published (per second)",
   "type": "timeseries",
   "description": "Number of successfully published messages, and messages that could not be published (due to rate limiting, bad formatting, etc.)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(ntfy_messages_published_success{job=\"$job\"}[$rate])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(ntfy_messages_published_failure{job=\"$job\"}[$rate])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Messages published",
   "type": "timeseries",
   "description": "Number of messages published since last ntfy server restart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "ntfy_messages_published_success{job=\"$job\"}",
     "legendFormat": "Successful"
    },
    {
     "expr": "ntfy_messages_published_failure{job=\"$job\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Messages cached",
   "type": "timeseries",
   "description": "Number of messages currently stored in message cache",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "ntfy_messages_cached_total{job=\"$job\"}",
     "legendFormat": "Messages in database"
    }
   ]
  },
  {
   "title": "Visitors, subscribers, topics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "ntfy_visitors_total{job=\"$job\"}",
     "legendFormat": "Visitors"
    },
    {
     "expr": "ntfy_topics_total{job=\"$job\"}",
     "legendFormat": "Topics"
    },
    {
     "expr": "ntfy_subscribers_total{job=\"$job\"}",
     "legendFormat": "Subscribers"
    },
    {
     "expr": "ntfy_users_total{job=\"$job\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "HTTP requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(job) (rate(ntfy_http_requests_total{job=\"$job\"}[$rate]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "HTTP errors (per second, excl. 429/507)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum by(http_code) (rate(ntfy_http_requests_total{job=\"$job\", http_code!=\"200\", http_code!=\"429\", http_code!=\"507\"}[$rate]))",
     "legendFormat": "{{http_code}}"
    }
   ]
  },
  {
   "title": "HTTP errors (per second, ntfy code)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "sum by(ntfy_code) (rate(ntfy_http_requests_total{http_code!=\"200\", job=\"$job\"}[$rate]))",
     "legendFormat": "{{http_method}} {{http_code}} {{ntfy_code}}"
    }
   ]
  },
  {
   "title": "Attachments: Total cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ntfy_attachments_total_size{job=\"$job\"}",
     "legendFormat": "Total size in MB"
    }
   ]
  },
  {
   "title": "Firebase messages sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "rate(ntfy_firebase_published_success{job=\"$job\"}[$rate])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(ntfy_firebase_published_failure{job=\"$job\"}[$rate])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "UnifiedPush messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(ntfy_unifiedpush_published_success{job=\"$job\"}[$rate])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(ntfy_http_requests_total{job=\"$job\",http_code=\"507\"}[$rate])",
     "legendFormat": "Rejected (HTTP 507)"
    }
   ]
  },
  {
   "title": "Matrix messages published",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "rate(ntfy_matrix_published_success{job=\"$job\"}[$rate])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(ntfy_matrix_published_failure{job=\"$job\"}[$rate])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Emails sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "ntfy_emails_sent_success{job=\"$job\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "ntfy_emails_sent_failure{job=\"$job\"}",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Emails received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "ntfy_emails_received_success{job=\"$job\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "ntfy_emails_received_failure{job=\"$job\"}",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Message publish duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ntfy_message_publish_duration_ms{job=\"$job\"}",
     "legendFormat": "Duration"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Go routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "Go routines"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "process_max_fds{job=\"$job\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Resident/virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "Resident memory used by ntfy (RSS)"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "Virtual memory used by ntfy (VSS)"
    }
   ]
  }
 ]
}