{
 "title": "Finance Exporter",
 "time": { "from": "now/d+9h+30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "stocks",
    "query": {
     "query": "label_values(finance_current_price, ticker)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$stocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "stocks" },
  {
   "title": "Stock Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "finance_current_price{ticker=~\"$stocks\"}"
    },
    {
     "expr": "finance_day_high{ticker=~\"$stocks\"}"
    },
    {
     "expr": "finance_day_low{ticker=~\"$stocks\"}"
    },
    {
     "expr": "finance_beta{ticker=~\"$stocks\"}"
    },
    {
     "expr": "finance_pe_forward{ticker=~\"$stocks\"}"
    },
    {
     "expr": "finance_pe_trailing{ticker=~\"$stocks\"}"
    },
    {
     "expr": "finance_volume{ticker=~\"$stocks\"} / finance_avg_10day_volume{ticker=~\"$stocks\"}"
    },
    {
     "expr": "finance_open_price{ticker=~\"$stocks\"}"
    },
    {
     "expr": "changes(finance_day_high{ticker=~\"$stocks\"}[$__range])"
    },
    {
     "expr": "changes(finance_day_low{ticker=~\"$stocks\"}[$__range])"
    },
    {
     "expr": "finance_rating{ticker=~\"$stocks\"}",
     "legendFormat": "Rating"
    },
    {
     "expr": "max(finance_current_price{ticker=~\"$stocks\"} offset 1d) by (ticker)",
     "legendFormat": "Previous Max"
    },
    {
     "expr": "max(finance_previous_close{ticker=~\"$stocks\"}) by (ticker)",
     "legendFormat": "Previous Close"
    }
   ]
  },
  {
   "title": "Today Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(finance_current_price{ticker=~\"$stocks\"}) by (ticker) - max(finance_open_price{ticker=~\"$stocks\"}) by (ticker)"
    }
   ]
  },
  {
   "title": "Stock Trend $stocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg(finance_current_price{ticker=~\"$stocks\"}) by (ticker)",
     "legendFormat": "{{ticker}} Price"
    },
    {
     "expr": "avg(finance_day_low{ticker=~\"$stocks\"}) by (ticker)",
     "legendFormat": "Day Low"
    },
    {
     "expr": "avg(finance_day_high{ticker=~\"$stocks\"}) by (ticker)",
     "legendFormat": "Day High"
    },
    {
     "expr": "avg(finance_open_price{ticker=~\"$stocks\"}) by (ticker)",
     "legendFormat": "Day Open"
    },
    {
     "expr": "avg(avg_over_time(finance_current_price{ticker=~\"$stocks\"}[1h])) by (ticker)",
     "legendFormat": "{{ticker}} SMA (120)"
    }
   ]
  },
  {
   "title": "Current Price / Target Offset",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(finance_current_price{ticker=~\"$stocks\"}) by (ticker)",
     "legendFormat": "Price"
    },
    {
     "expr": "min(finance_current_price{ticker=~\"$stocks\"}) by (ticker) - min(finance_target_median_price{ticker=~\"$stocks\"}) by (ticker)",
     "legendFormat": "Offset"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "avg(rate(finance_volume{ticker=~\"$stocks\"}[$__interval])) by (ticker)",
     "legendFormat": "{{ticker}} Volume"
    }
   ]
  },
  {
   "title": "Yesterday Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(finance_current_price{ticker=~\"$stocks\"}) by (ticker) - min(finance_previous_close{ticker=~\"$stocks\"}) by (ticker)",
     "legendFormat": "{{ticker}}"
    }
   ]
  }
 ]
}