# /etc/opt/traefik/config/dynamic/traefik.yml
# References:
#   - https://www.authelia.com/integration/proxies/traefik/
#   - https://www.simplecto.com/use-traefik-with-nginx-apache-caddyserver-serve-static-files/
#   - https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
http:
  routers:
    traefik: &service
      rule: Host(`secproxy.{{ site.url }}`)
      entryPoints: websecure
      service: api@internal
      middlewares:
        - authelia@file
        - secure-headers@file
      tls:
        options: intermediate@file
        certResolver: le-http-production
    authelia:
      <<: *service
      rule: Host(`auth.{{ site.url }}`)
      service: authelia@file
      middlewares:
        - secure-headers@file
    lldap:
      <<: *service
      rule: Host(`ldap.{{ site.url }}`)
      service: lldap@file
    gatus:
      <<: *service
      rule: Host(`uptime.{{ site.url }}`)
      service: gatus@file
    grafana:
      <<: *service
      rule: Host(`graph.{{ site.url }}`)
      service: grafana@file
    victoriametrics:
      <<: *service
      rule: Host(`metrics.{{ site.url }}`)
      service: victoriametrics@file
    victorialogs:
      <<: *service
      rule: Host(`logs.{{ site.url }}`)
      service: victorialogs@file
    vmalert:
      <<: *service
      rule: Host(`alert.{{ site.url }}`)
      service: vmalert@file
    alertmanager:
      <<: *service
      rule: Host(`alertmanager.{{ site.url }}`)
      service: alertmanager@file
    # vault:
    #   <<: *service
    #   rule: Host(`vault.{{ site.url }}`)
    #   service: vault@file
    # hass:
    #   <<: *service
    #   rule: Host(`hass.{{ site.url }}`)
    #   service: hass@file
  services:
    authelia:
      loadBalancer:
        servers:
          - url: https://auth.{{ site.url }}:9091/
        serversTransport: autheliaMutualTLS
    lldap:
      loadBalancer:
        servers:
          - url: http://ldap.{{ site.url }}:17170/
    gatus:
      loadBalancer:
        servers:
          - url: http://uptime.{{ site.url }}:8080/
    grafana:
      loadBalancer:
        servers:
          - url: http://graph.{{ site.url }}:3000/
    victoriametrics:
      loadBalancer:
        servers:
          - url: http://metrics.{{ site.url }}:8428/vmui/
    victorialogs:
      loadBalancer:
        servers:
          - url: http://logs.{{ site.url }}:9428/select/vmui/
    vmalert:
      loadBalancer:
        servers:
          - url: http://alert.{{ site.url }}:8880/
    alertmanager:
      loadBalancer:
        servers:
          - url: http://alertmanager.{{ site.url }}:9093/
    # vault:
    #   loadBalancer:
    #     servers:
    #       - url: http://vault.{{ site.url }}:80/
    # hass:
    #   loadBalancer:
    #     servers:
    #       - url: https://homesvcs.{{ site.url }}:443/
