# /etc/opt/traefik/config/dynamic/routes.yml
# References:
#   - https://www.authelia.com/integration/proxies/traefik/
#   - https://www.simplecto.com/use-traefik-with-nginx-apache-caddyserver-serve-static-files/
#   - https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
#   - https://doc.traefik.io/traefik/routing/routers/#priority
# yamllint disable rule:document-start rule:document-end
http:
  routers:
    traefik: &service
      rule: Host(`secproxy.{{ site.url }}`)
      entryPoints: websecure
      service: api@internal
      middlewares:
        - authelia@file
        - secure-headers@file
      tls:
        options: intermediate@file
        certResolver: le-http-production
    authelia:
      <<: *service
      rule: Host(`auth.{{ site.url }}`)
      service: authelia@file
      middlewares:
        - secure-headers@file
    lldap:
      <<: *service
      rule: Host(`ldap.{{ site.url }}`)
      service: lldap@file
    gatus:
      <<: *service
      rule: Host(`uptime.{{ site.url }}`)
      service: gatus@file
    grafana:
      <<: *service
      rule: Host(`graph.{{ site.url }}`)
      service: grafana@file
    victoriametrics-ui:
      <<: *service
      rule: Host(`metrics.{{ site.url }}`) && HeaderRegexp(`User-Agent`, `^Mozilla\/.*`)
      service: victoriametrics@file
      middlewares:
        - authelia@file
        - vm-auth@file
        - secure-headers@file
    victoriametrics-api:
      <<: *service
      rule: Host(`metrics.{{ site.url }}`)
      service: victoriametrics@file
      middlewares: []
    victorialogs-ui:
      <<: *service
      rule: Host(`logs.{{ site.url }}`) && HeaderRegexp(`User-Agent`, `^Mozilla\/.*`)
      service: victorialogs@file
      middlewares:
        - authelia@file
        - vl-auth@file
        - secure-headers@file
    victorialogs-api:
      <<: *service
      rule: Host(`logs.{{ site.url }}`)
      service: victorialogs@file
      middlewares: []
    vmalert:
      <<: *service
      rule: Host(`vmalert.{{ site.url }}`)
      service: vmalert@file
    alertmanager-ui:
      <<: *service
      rule: Host(`alert.{{ site.url }}`) && HeaderRegexp(`User-Agent`, `^Mozilla\/.*`)
      service: alertmanager@file
      middlewares:
        - authelia@file
        - alertmanager-auth@file
        - secure-headers@file
    alertmanager-api:
      <<: *service
      rule: Host(`alert.{{ site.url }}`)
      service: alertmanager@file
      middlewares: []
    ntfy-ui:
      <<: *service
      # Ref: https://github.com/binwiederhier/ntfy/issues/893#issuecomment-1731314679
      rule: Host(`push.{{ site.url }}`) && HeaderRegexp(`User-Agent`, `^Mozilla\/.*`) && !PathPrefix(`/file/`)
      service: ntfy@file
      middlewares:
        - authelia@file
        - ntfy-auth@file
        - secure-headers@file
    ntfy-api:
      <<: *service
      rule: Host(`push.{{ site.url }}`)
      service: ntfy@file
      middlewares: []
    ntfy-alertmanager:
      <<: *service
      rule: Host(`ntfy-alertmanager.{{ site.url }}`)
      service: ntfy-alertmanager@file
      middlewares: []
    # vault:
    #   <<: *service
    #   rule: Host(`vault.{{ site.url }}`)
    #   service: vault@file
  services:
    authelia:
      loadBalancer:
        servers:
          - url: https://auth.{{ site.url }}:9091/
        serversTransport: autheliaMutualTLS
    lldap:
      loadBalancer:
        servers:
          - url: http://ldap.{{ site.url }}:17170/
    gatus:
      loadBalancer:
        servers:
          - url: http://uptime.{{ site.url }}:8080/
    grafana:
      loadBalancer:
        servers:
          - url: http://graph.{{ site.url }}:3000/
    victoriametrics:
      loadBalancer:
        servers:
          - url: http://metrics.{{ site.url }}:8428/
    victorialogs:
      loadBalancer:
        servers:
          - url: http://logs.{{ site.url }}:9428/
    vmalert:
      loadBalancer:
        servers:
          - url: http://vmalert.{{ site.url }}:8880/
    alertmanager:
      loadBalancer:
        servers:
          - url: http://alert.{{ site.url }}:9093/
    ntfy:
      loadBalancer:
        servers:
          - url: http://push.{{ site.url }}:2586/
    ntfy-alertmanager:
      loadBalancer:
        servers:
          - url: http://ntfy-alertmanager.{{ site.url }}:2588/
    # vault:
    #   loadBalancer:
    #     servers:
    #       - url: http://vault.{{ site.url }}:80/
